// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7EPvJqPLTq5mKAz_9dfcA2IoH3j_GIyw',
    appId: '1:1018634080821:web:f3635c27084e7c84c5577c',
    messagingSenderId: '1018634080821',
    projectId: 'tzamtzamhadar',
    authDomain: 'tzamtzamhadar.firebaseapp.com',
    storageBucket: 'tzamtzamhadar.appspot.com',
    measurementId: 'G-2S5Z3JXTVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXVcwsNlSli35vAD0T3ROYe5WZDZQyM2I',
    appId: '1:1018634080821:android:38947e14c631bb63c5577c',
    messagingSenderId: '1018634080821',
    projectId: 'tzamtzamhadar',
    storageBucket: 'tzamtzamhadar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA44tNWYcWjfH2qp8brzJgnVdp2iUhKWM0',
    appId: '1:1018634080821:ios:421c277a8bcb61ffc5577c',
    messagingSenderId: '1018634080821',
    projectId: 'tzamtzamhadar',
    storageBucket: 'tzamtzamhadar.appspot.com',
    iosBundleId: 'com.example.tzamtzamHadar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA44tNWYcWjfH2qp8brzJgnVdp2iUhKWM0',
    appId: '1:1018634080821:ios:395a35ea9af6c685c5577c',
    messagingSenderId: '1018634080821',
    projectId: 'tzamtzamhadar',
    storageBucket: 'tzamtzamhadar.appspot.com',
    iosBundleId: 'com.example.tzamtzamHadar.RunnerTests',
  );
}
